### ISSUE TITLE
Better handling for 404 responses needed

### ISSUE THREAD

**Issue by benzimmer** [yammer/yam#46]
Currently if I do something like this for a thread that has been deleted from Yammer

``` ruby
deleted_thread_id = 12345
yamr = Yammer::Client.new(:access_token  => '123abc')
resp = yamr.get_thread(deleted_thread_id)
```

`resp` will be `" "` (String with a single space). I understand that you don't wan't to handle every kind of exception that can happen, but I think at least 404 should be handled better than that.

**Comment by mrbriandavis** [comment]
@benzimmer - Thanks for the feedback. I am going to take a look into fixing this soon.
